### PR TITLE
feat: adds option to turn off performance metrics

### PR DESCRIPTION
**Pull request by HarryEMartland**

### CODE REVIEW

**Comment by lholmquist** [comment]
@HarryEMartland thanks for this

I wonder if it would make more sense to make the second argument, an object that contained the options instead of adding another argument to the signature.

so instead of:  
```new PrometheusMetrics([c1], null, {exposePerformanceMetrics: false});```

 it could be: 
```new PrometheusMetrics([c1], {registry: 'something', exposePerformanceMetrics: false});```


This would of course be a breaking change.

**Comment by HarryEMartland** [comment]
Yes, I agree that is better. I could look into doing a migration strategy so this is not a breaking version or do you not worry too much about breaking versions?
Happy to make the change.

**Comment by lholmquist** [comment]
the version is only at 0.1.0,  so breaking changes i think are expected,  as long as we document it :)

**Comment by HarryEMartland** [comment]
What are your thoughts about putting the circuit breakers into the options object as well? That would tidy up the code around if the first argument is a registry or circuit breakers.

**Comment by lholmquist** [comment]
> What are your thoughts about putting the circuit breakers into the options object as well? That would tidy up the code around if the first argument is a registry or circuit breakers.

hmmmm,  maybe.  lets see how it would look

**Comment by HarryEMartland** [comment]
I have raised #19 which uses an options object to register initial circuit breakers.

**Pull request closed without merging**
