### PR TITLE
Add stats (percentiles stats, reponse times) in Prometheus metrics

### PR DESCRIPTION
**Pull request by franckOL**

### CODE REVIEW

**Comment by lholmquist** [comment]
Looks like the commit history is a little messy here.  i would suggest creating a new branch for each different PR you send

**Comment by franckOL** [comment]
Yes this a new branch `feat\summarystats`, i try what you want , something else is missing then :-)

**Comment by lance** [comment]
@franckOL perhaps you can rebase this branch against `master`? The commit history here has several commits that have been merged into master already.

**Comment by franckOL** [comment]
@lance, does that means merge the feature branche on master on master ?

**Comment by lance** [comment]
Here are the steps that I would take.

```console
git fetch
git co feat/summarystats
git rebase origin master
# This will probably result in some conflicts that you will need to manually resolve.
# Resolve them by editing the change conflicts, then run 'git add path/to/conflict/file'
# Then run 'git rebase --continue'
```

You will need to force push these changes.

**Comment by franckOL** [comment]
Hum, I think this OK. Commit history not very clean

**Comment by franckOL** [comment]
Must have i do something to help progression of the PR ?

**Comment by lholmquist** [comment]
@franckOL There is definently somehting going on with the commit history.

As much as a pain as it might be,  it might be good to create a fresh branch from the most recent master and then copy and paste the changes you did

**Comment by franckOL** [comment]
@lance : Restarting for scratch ==> see #10

**Comment by lance** [comment]
Superseded by: https://github.com/nodeshift/opossum-prometheus/pull/9

**Pull request closed without merging**
